### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by IshaanJivani** [KangweiZhu/lyrics-on-panel#1]
I really appreciate this plugin and by the look of it it looks so good already.

However, how do we even get this widget installed?
there's no <>.plasmoid file and kde can't even directly install from tarball.

Thanks and please help.

**Comment by IshaanJivani** [comment]
Nvm was blind ig

**Comment by KangweiZhu** [comment]
Glad to hear you've found a solution!  Reallly thanks for your nice words!
I'll add the installation guide to the readme file.
